import game_world
import game_framework

PIXEL_PER_METER = (140.0 / 0.18) # 140 pixel 18 cm
BIRD_FLY_SPEED_KMPH = 38.0 # Km / Hour
BIRD_FLY_SPEED_MPM = (BIRD_FLY_SPEED_KMPH * 1000.0 / 60.0)
BIRD_FLY_SPEED_MPS = (BIRD_FLY_SPEED_MPM / 60.0)
BIRD_FLY_SPEED_PPS = (BIRD_FLY_SPEED_MPS * PIXEL_PER_METER)